In [1]:
# TASK 2 SIMPLE TEXT CLASSIFICATION
def gender_features(word):
    return {'last_letter': word[-1]}

In [2]:
gender_features('Obama')

{'last_letter': 'a'}

In [3]:
from nltk.corpus import names
#names.word()
print(len(names.words()))

7944


In [4]:
labeled_names = ([(name, 'male') for name in names.words('male.txt')] + [(name, 'female') for name in names.words('female.txt')])
labeled_names

[('Aamir', 'male'),
 ('Aaron', 'male'),
 ('Abbey', 'male'),
 ('Abbie', 'male'),
 ('Abbot', 'male'),
 ('Abbott', 'male'),
 ('Abby', 'male'),
 ('Abdel', 'male'),
 ('Abdul', 'male'),
 ('Abdulkarim', 'male'),
 ('Abdullah', 'male'),
 ('Abe', 'male'),
 ('Abel', 'male'),
 ('Abelard', 'male'),
 ('Abner', 'male'),
 ('Abraham', 'male'),
 ('Abram', 'male'),
 ('Ace', 'male'),
 ('Adair', 'male'),
 ('Adam', 'male'),
 ('Adams', 'male'),
 ('Addie', 'male'),
 ('Adger', 'male'),
 ('Aditya', 'male'),
 ('Adlai', 'male'),
 ('Adnan', 'male'),
 ('Adolf', 'male'),
 ('Adolfo', 'male'),
 ('Adolph', 'male'),
 ('Adolphe', 'male'),
 ('Adolpho', 'male'),
 ('Adolphus', 'male'),
 ('Adrian', 'male'),
 ('Adrick', 'male'),
 ('Adrien', 'male'),
 ('Agamemnon', 'male'),
 ('Aguinaldo', 'male'),
 ('Aguste', 'male'),
 ('Agustin', 'male'),
 ('Aharon', 'male'),
 ('Ahmad', 'male'),
 ('Ahmed', 'male'),
 ('Ahmet', 'male'),
 ('Ajai', 'male'),
 ('Ajay', 'male'),
 ('Al', 'male'),
 ('Alaa', 'male'),
 ('Alain', 'male'),
 ('Alan', 'male

In [7]:
import random
random.shuffle(labeled_names)

In [8]:
featuresets = [(gender_features(n), gender) for (n, gender) in labeled_names]

In [9]:
featuresets

[({'last_letter': 'n'}, 'female'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'e'}, 'male'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'l'}, 'male'),
 ({'last_letter': 'l'}, 'female'),
 ({'last_letter': 'e'}, 'female'),
 ({'last_letter': 'd'}, 'male'),
 ({'last_letter': 'y'}, 'male'),
 ({'last_letter': 'e'}, 'female'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 't'}, 'male'),
 ({'last_letter': 'y'}, 'female'),
 ({'last_letter': 's'}, 'male'),
 ({'last_letter': 'h'}, 'female'),
 ({'last_letter': 't'}, 'female'),
 ({'last_letter': 'e'}, 'female'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'r'}, 'male'),
 ({'last_letter': 'n'}, 'male'),
 ({'last_letter': 'y'}, 'female'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 's'}, 'male'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 's'}, 'female'),
 ({'last_letter': 'e'}, 'female'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'm'}, 'male'),
 ({'l

In [10]:
train_set, test_set = featuresets[:5000], featuresets[5000:]

In [38]:
import nltk
classifier = nltk.NaiveBayesClassifier.train(train_set)

In [12]:
classifier.classify(gender_features('David'))

'male'

In [13]:
classifier.classify(gender_features('Yann Lecun'))

'male'

In [27]:
classifier.classify(gender_features('Sharmila Banu'))

'male'

In [48]:
print(nltk.classify.accuracy(classifier, test_set))

0.7622282608695652


In [58]:
print(nltk.classify.accuracy(classifier, test_set))

0.7622282608695652


In [62]:
# TASK 3 COUNT VECTORIZER
from sklearn.feature_extraction.text import CountVectorizer

In [63]:
vect = CountVectorizer(binary = True)
corpus = ["Tessaract is good optical character recognition engine", "optical character recognition is significant"]

In [64]:
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [68]:
vocab = vect.vocabulary_
print(vocab)

{'tessaract': 7, 'is': 3, 'good': 2, 'optical': 4, 'character': 0, 'recognition': 5, 'engine': 1, 'significant': 6}


In [69]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [70]:
print(vect.transform(["This is a good optical illusion"]).toarray())

[[0 0 1 1 1 0 0 0]]


In [89]:
# We're comparing Obama's Speech and Trump's Speech
from nltk.corpus import inaugural
obamaSpeech = inaugural.words(fileids = '2009-Obama.txt')
trumpSpeech = inaugural.words(fileids = '2017-Trump.txt')
obamaSpeech = " ".join(obamaSpeech)
obamaSpeech = " ".join(trumpSpeech)
documents = [obamaSpeech, trumpSpeech]

In [95]:
from nltk.corpus import inaugural
from sklearn.feature_extraction.text import CountVectorizer
obamaSpeech = inaugural.words(fileids = '2009-Obama.txt')
trumpSpeech = inaugural.words(fileids = '2017-Trump.txt')
obamaSpeech = " ".join(obamaSpeech)
trumpSpeech = " ".join(trumpSpeech)
documents = [str(obamaSpeech), str(trumpSpeech)]

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Create the Document Term Matrix
count_vectorizer = CountVectorizer(stop_words='english')
sparse_matrix = count_vectorizer.fit_transform(documents)

doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, columns=count_vectorizer.get_feature_names(), index=['obamaSpeech', 'trumpSpeech'])
print(df)

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(sparse_matrix[0:1], sparse_matrix)

             20  2017  abandoned  ability  accept  account  achieve  act  \
obamaSpeech   0     0          1        1       1        1        1    1   
trumpSpeech   1     1          0        0       1        0        0    0   

             action  administration  ...  workers  works  world  worldly  \
obamaSpeech       1               0  ...        2      1      7        1   
trumpSpeech       2               1  ...        2      0      6        0   

             worn  wrong  year  years  yes  young  
obamaSpeech     1      1     2      1    1      1  
trumpSpeech     0      0     0      2    1      1  

[2 rows x 1020 columns]


array([[1.        , 0.48538775]])

In [97]:
# Finding Similarity with stemming

from nltk.corpus import inaugural
from sklearn.feature_extraction.text import CountVectorizer
obamaSpeech = inaugural.words(fileids = '2009-Obama.txt')
trumpSpeech = inaugural.words(fileids = '2017-Trump.txt')

from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
obamaSpeech = [stemmer.stem(token) for token in obamaSpeech]
trumpSpeech = [stemmer.stem(token) for token in trumpSpeech]

obamaSpeech = " ".join(obamaSpeech)
trumpSpeech = " ".join(trumpSpeech)
documents = [str(obamaSpeech), str(trumpSpeech)]

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Create the Document Term Matrix
count_vectorizer = CountVectorizer(stop_words='english')
sparse_matrix = count_vectorizer.fit_transform(documents)

doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, columns=count_vectorizer.get_feature_names(), index=['obamaSpeech', 'trumpSpeech'])
print(df)

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(sparse_matrix[0:1], sparse_matrix)

             20  2017  abandon  abil  accept  account  achiev  act  action  \
obamaSpeech   0     0        1     1       1        1       1    1       1   
trumpSpeech   1     1        0     0       1        0       0    0       2   

             administr  ...  word  work  worker  world  worldli  worn  wrong  \
obamaSpeech          0  ...     4     8       2      7        1     1      1   
trumpSpeech          1  ...     1     1       2      6        0     0      0   

             ye  year  young  
obamaSpeech   1     3      1  
trumpSpeech   1     2      1  

[2 rows x 899 columns]


array([[1.        , 0.59084633]])

# Conclusion: We're able to achieve a similarity of 48.53% without stemming and a 59.084% with stemming.
# We're able to see that a little preprocessing helps us get more similarity. Hence, stemming is uselful in finding similarity between two documents and aso in understanding plagiarism
# Google search engine would use text preprocessing techniques of stemming and lemmatization to achieve a greater accuracy of search results. This helps in providing more number of results to the end user.